#!/usr/bin/env bash
# script to display information about a subdomain

# print information about a subdomain
domain_info() {
	local domain="$1"
	local subdomain="$2"
	local line
	line=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
	echo "The subdomain $subdomain is a $(awk 'NR==1{print $1}' <<< "$line") record and points to $(awk 'NR==1{print $2}' <<< "$line")"
}	

if [ "$#" -eq 1 ]; then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	domain_info "$1" "$2"
fi
